In [45]:
import pathlib
import pandas as pd
import xml.etree.ElementTree as et
import numpy as np

# define the path
currentDirectory = pathlib.Path('../../CoE_dataset/Test_Set/XML')

# define the pattern
currentPattern = "*.xml"
all_xml_files = []
for currentFile in currentDirectory.glob(currentPattern):
    all_xml_files.append(currentFile.parts[-1])
    
print(all_xml_files)

['Sleeping_Beauty.xml', 'Foxcatcher.xml', 'The_Trip_to_Italy.xml', 'A_Little_Chaos.xml', 'Bad_News_Bears.xml', 'Run_Lola_Run.xml', 'Love_Actually.xml', '12_Years_a_Slave.xml', 'Kundo__Age_of_the_Rampant.xml', 'The_Best_of_Me.xml', 'A_Most_Wanted_Man.xml', 'The_Simpsons_Movie.xml', 'Homeland.xml', 'Bride_Flight.xml', 'Rise_of_the_Planet_of_the_Apes.xml', 'Banklady.xml', 'Silver_Linings_Playbook.xml', 'Godzilla.xml', 'Antz.xml', 'The_Hobbit__An_Unexpected_Journey.xml', 'The_Shawshank_Redemption.xml', 'Mr._Turner.xml', 'Hum_Aapke_Hain_Koun...!.xml', 'Legally_Blonde.xml', 'The_Inglorious_Bastards.xml', 'Soof.xml', 'Testament_of_Youth.xml', 'Dilwale_Dulhania_Le_Jayenge.xml', 'Prometheus.xml', 'Maps_to_the_Stars.xml', 'Bewakoofiyaan.xml', 'Big_Game.xml', 'Blow_Out.xml', 'Fast_Five.xml', 'Verliefd_op_Ibiza.xml', 'Leviathan.xml', 'The_English_Patient.xml', 'And_So_It_Goes.xml', 'Alice_in_Wonderland.xml', 'The_Great_Escape.xml', 'Smokey_and_the_Bandit.xml', 'Magic_in_the_Moonlight.xml', 'Edge_of_Tomorrow.xml', 'Cascadeur.xml', 'Lilting.xml', 'Begin_Again.xml', 'The_Big_Chill.xml', 'The_Silence_of_the_Lambs.xml', 'The_Green_Mile.xml', 'Star_Wars__Episode_IV_-_A_New_Hope.xml', 'Finding_Nemo.xml', 'Walk_the_Line.xml', 'The_Mummy.xml', 'Mommie_Dearest.xml', 'Harry_Potter_and_the_Deathly_Hallows__Part_2.xml', 'The_Incredibles.xml', 'The_Grand_Budapest_Hotel.xml', 'The_Wolf_of_Wall_Street.xml', 'Gunday.xml', 'The_Social_Network.xml', 'Beetlejuice.xml', 'Dolphin_Tale_2.xml', 'A_Simple_Life.xml', 'Titanic.xml', 'Humpty_Sharma_Ki_Dulhania.xml', 'The_Drop.xml', 'Pocahontas.xml', 'The_Croods.xml', 'Iron_Man_3.xml', 'Miss_Sixty.xml', 'Katalin_Varga.xml', 'Justin_Bieber__Never_Say_Never.xml', 'Yentl.xml', 'Warrior.xml', 'Dorsvloer_vol_confetti.xml', 'Iron_Man_2.xml', 'Maleficent.xml', 'Kurt_Cobain__Montage_of_Heck.xml', 'Aanmodderfakker.xml', 'Rab_Ne_Bana_Di_Jodi.xml', 'La_foresta_di_ghiaccio.xml', 'The_Talented_Mr._Ripley.xml', 'Loft.xml', 'Wet_Hot_American_Summer.xml', 'Happy_New_Year.xml', 'Karan_Arjun.xml', 'The_Girl_with_the_Dragon_Tattoo.xml', 'Limitless.xml', 'Lucy.xml', '2_States.xml', 'Mary_Kom.xml', 'Lost_Highway.xml', 'Fargo.xml', 'The_AristoCats.xml', 'Gooische_vrouwen.xml', 'Valkyrie.xml', 'The_Queen.xml', 'Thor__The_Dark_World.xml', 'The_Expendables_3.xml', 'Mommy.xml', 'Whiplash.xml', 'The_Gambler.xml', 'PK.xml', 'Alexander.xml', 'One_Chance.xml', 'John_Tucker_Must_Die.xml', 'Ironclad.xml', 'Trainspotting.xml', 'Heaven_Knows_What.xml', 'Charlie_and_the_Chocolate_Factory.xml', 'Contact.xml', 'Million_Dollar_Arm.xml', 'Zombieland.xml', 'Rocky_Balboa.xml', 'Dumb_and_Dumber_To.xml', 'Groundhog_Day.xml', 'Stardust.xml', 'Life_of_Crime.xml', 'New_Kids_Nitro.xml', 'The_Golden_Era.xml', 'Moonrise_Kingdom.xml', 'The_Lego_Movie.xml', "The_King's_Speech.xml", 'I_Am_Big_Bird__The_Caroll_Spinney_Story.xml', 'Avatar.xml', 'Dracula_Untold.xml', 'Neighbors.xml', 'Mardaani.xml', 'Interview_with_the_Vampire__The_Vampire_Chronicles.xml', 'The_Equalizer.xml', 'Pirates_of_the_Caribbean__The_Curse_of_the_Black_Pearl.xml', 'Guardians_of_the_Galaxy.xml', 'The_Monuments_Men.xml', 'The_Rewrite.xml', 'What_We_Do_in_the_Shadows.xml', 'Fury.xml', 'Divergent.xml', 'Belle_de_Jour.xml', 'Hector_and_the_Search_for_Happiness.xml', 'Sleepy_Hollow.xml', 'Hungry_Hearts.xml', 'X-Men__Days_of_Future_Past.xml', '10.000_Km.xml', 'Hercules.xml', 'The_Avengers.xml', '21_Jump_Street.xml', 'Se7en.xml', 'Serena.xml', 'Soul_Surfer.xml', 'Dumbo.xml', 'Flying_Home.xml', 'Wassup_Rockers.xml', 'The_Departed.xml', 'Gone_Girl.xml', 'Watchmen.xml', 'Burlesque.xml', 'Tammy.xml', 'Frozen.xml', 'My_Own_Private_Idaho.xml', 'Billy_Elliot.xml', 'The_Water_Diviner.xml', 'Bhoothnath.xml', 'The_Hangover.xml', 'The_White_Haired_Witch_of_Lunar_Kingdom.xml', 'Kick-Ass_2.xml', 'The_Hobbit__The_Battle_of_the_Five_Armies.xml', 'Mr.___Mrs._Smith.xml', 'Django_Unchained.xml', 'Good_Morning,_Vietnam.xml', 'La_Vie_en_Rose.xml', 'Pak_Van_Mijn_Hart.xml', 'Horrible_Bosses_2.xml', 'The_Devil_Wears_Prada.xml', 'Quantum_of_Solace.xml', 'Captain_America__The_Winter_Soldier.xml', 'The_Bridges_of_Madison_County.xml', 'Birdman__Or_(The_Unexpected_Virtue_of_Ignorance).xml', 'Who_Framed_Roger_Rabbit.xml', 'La_Camioneta__The_Journey_of_One_American_School_Bus.xml', 'American_Sniper.xml', 'From_A_to_B.xml', 'Yves_Saint_Laurent.xml', 'Finding_Fanny.xml', 'The_Voices.xml', 'Blended.xml', 'Oliver___Company.xml', 'There_Will_Be_Blood.xml', 'Love,_Rosie.xml', 'Kingsman__The_Secret_Service.xml', 'Kick-Ass.xml', 'Clash_of_the_Titans.xml', 'Trash.xml', 'Unbroken.xml', 'Dances_with_Wolves.xml', 'Mrs._Doubtfire.xml', 'Padosan.xml', 'Alexander_and_the_Terrible,_Horrible,_No_Good,_Very_Bad_Day.xml', 'How_to_Train_Your_Dragon_2.xml', 'Pride___Prejudice.xml', 'X-Men__First_Class.xml', 'The_Hundred-Foot_Journey.xml', 'Tommy_Boy.xml', 'Moonstruck.xml', 'The_Girl_Next_Door.xml', 'Magic_Mike.xml', 'In_Her_Shoes.xml', 'The_Face_Reader.xml', 'School_of_Rock.xml', 'The_Little_Mermaid.xml', 'Anastasia.xml', 'The_Fox_and_the_Hound.xml', 'Good_People.xml', 'Paddington.xml', 'Thelma___Louise.xml', 'Selma.xml', 'Wish_I_Was_Here.xml', "A_Bug's_Life.xml", 'Bridges_of_Sarajevo.xml', 'Gran_Torino.xml', 'Good_Will_Hunting.xml', 'The_Good,_the_Bad_and_the_Ugly.xml', 'Ratatouille.xml', 'Oorlogswinter.xml']

In [46]:
def parse_XML(xml_file, name, df_cols):
            global out_df

            xtree = et.parse(xml_file)
            xroot = xtree.getroot()
            fin = []
            res = []
            res.append(name[:-4])
            
            for node in xroot:
                for i in node_cols:
                    res.append(node.attrib.get(i))

            fin.append(res)
            print(fin)
            out_df = pd.DataFrame(data=fin, columns =meta_cols)
            return out_df
        
def parse_XML1(xml_file, name, df_cols, df):
            global out_df
            xtree = et.parse(xml_file)
            xroot = xtree.getroot()
            fin = []
            res = []
            res.append(name[:-4])
            for node in xroot:
                for i in node_cols:
                    res.append(node.attrib.get(i))

            fin.append(res)
            df1 = pd.DataFrame(data=fin, columns =meta_cols)
            
            frames = [df, df1]
            
            out_df = pd.concat(frames)
            
            return out_df

In [47]:
meta_cols = ["filename","language", "year", "genre", "country",
            "runtime", "rated", "imdbRating","tomatoRating","tomatoUserRating","metascore"]

node_cols = ["language", "year", "genre", "country",
            "runtime", "rated","imdbRating","tomatoRating","tomatoUserRating","metascore"]

In [48]:
c = 1
for i in all_xml_files:
    if c==1:
        parse_XML("data/Test_Set/XML/" + i, i,  meta_cols)
        c=43
    else:
        parse_XML1("data/Test_Set/XML/"+i, i, meta_cols, out_df)

[['Sleeping_Beauty', 'English', '1959', 'Animation, Family, Fantasy', 'USA', '75 min', 'APPROVED', '7.3', '8.1', '3.4', 'N/A']]

In [49]:
out_df["metascore"] = pd.to_numeric(out_df["metascore"], errors='coerce')
out_df["imdbRating"] = pd.to_numeric(out_df["imdbRating"], errors='coerce')
out_df["tomatoUserRating"] = pd.to_numeric(out_df["tomatoUserRating"], errors='coerce')
out_df["tomatoRating"] = pd.to_numeric(out_df["tomatoRating"], errors='coerce')
#out_df.sort_values("filename")
out_df

,filename,language,year,genre,country,runtime,rated,imdbRating,tomatoRating,tomatoUserRating,metascore
0,Sleeping_Beauty,English,1959,"Animation, Family, Fantasy",USA,75 min,APPROVED,7.3,8.1,3.4,NaN
0,Foxcatcher,"English, French",2014,"Biography, Drama, Sport",USA,134 min,R,7.1,7.9,3.5,81.0
0,The_Trip_to_Italy,English,2014,"Comedy, Drama",UK,108 min,NOT RATED,6.7,7.3,3.2,75.0
0,A_Little_Chaos,English,2014,"Comedy, Drama, Romance",UK,117 min,R,6.4,5.4,3.3,50.0
0,Bad_News_Bears,"English, Spanish",2005,"Comedy, Family, Sport",USA,113 min,PG-13,5.8,NaN,3.3,65.0
...,...,...,...,...,...,...,...,...,...,...,...
0,Gran_Torino,"English, Hmong",2008,Drama,"USA, Germany",116 min,R,8.2,7.1,4.1,72.0
0,Good_Will_Hunting,English,1997,Drama,USA,126 min,R,8.3,8.0,3.9,70.0
0,"The_Good,_the_Bad_and_the_Ugly",Italian,1966,Western,"Italy, Spain, West Germany, USA",161 min,NOT RATED,8.9,8.8,4.0,90.0
0,Ratatouille,"English, French",2007,"Animation, Comedy, Family",USA,111 min,G,8.0,8.5,3.9,96.0
0,Oorlogswinter,Dutch,1975,Drama,Netherlands,325 min,N/A,6.7,NaN,NaN,NaN

In [62]:
df_ground = pd.read_csv("../../CoE_dataset/Test_Set/test_set_labels.csv", delimiter=";", quoting = 3)
# Rename columns for joining afterwards
df_ground.columns = ["movie", "filename", "goodforairplane"]
# Only for TestLabels because 2 files contain .mp4 ending
df_ground["filename"] = df_ground["filename"].str.replace(".mp4","")
# Because 4 lines have "" in their names
df_ground["movie"] = df_ground["movie"].str.replace('"',"")
df_ground["goodforairplane"] = df_ground["goodforairplane"].str.replace('"',"")
df_ground["goodforairplane"] = df_ground["goodforairplane"].astype(int)
# Check for duplicates
df_ground[df_ground.duplicated(["filename"])]
# Remove duplicates
# Remove movie which is not included in the test data
i = df_ground[df_ground["movie"] == "10.000_km"].index
j = df_ground[df_ground["filename"] == "A_Fish_Called_Wanda"].index
df_ground = df_ground.drop(i)
df_ground = df_ground.drop(j)
df_ground = df_ground.sort_values("movie")
df_ground
#df_ground.to_csv("test_labels_sorted_cleaned.csv",index=False)

                          movie                    filename  goodforairplane
74                    10.000 Km                   10.000_Km                1
155            12 Years a Slave            12_Years_a_Slave                1
182                    2 States                    2_States                1
91               21 Jump Street              21_Jump_Street                1
43                 A Bug's Life                A_Bug's_Life                1
..                          ...                         ...              ...
49   X-Men  Days of Future Past  X-Men__Days_of_Future_Past                0
19           X-Men  First Class          X-Men__First_Class                0
53                        Yentl                       Yentl                1
179          Yves Saint Laurent          Yves_Saint_Laurent                0
189                  Zombieland                  Zombieland                0

[223 rows x 3 columns]

In [44]:
#df_ground = pd.read_csv("data/Test_Set/test_set_labels.csv", delimiter=";", quoting = 3)
#df_ground.columns = ["movie", "filename", "goodforairplane"]
#a = df_ground["filename"].sort_values()
#b = out_df["filename"].sort_values()

#for i in a.values:
#    if i in b.values:
#        continue
#    else:
#        print(i)
#out_df

A_Fish_Called_Wanda
Birdman__Or_(The_Unexpected_Virtue_of_Ignorance).mp4
Hum_Aapke_Hain_Koun...!.mp4

,filename,language,year,genre,country,runtime,rated,imdbRating,tomatoRating,tomatoUserRating,metascore
0,Sleeping_Beauty,English,1959,"Animation, Family, Fantasy",USA,75 min,APPROVED,7.3,8.1,3.4,NaN
0,Foxcatcher,"English, French",2014,"Biography, Drama, Sport",USA,134 min,R,7.1,7.9,3.5,81.0
0,The_Trip_to_Italy,English,2014,"Comedy, Drama",UK,108 min,NOT RATED,6.7,7.3,3.2,75.0
0,A_Little_Chaos,English,2014,"Comedy, Drama, Romance",UK,117 min,R,6.4,5.4,3.3,50.0
0,Bad_News_Bears,"English, Spanish",2005,"Comedy, Family, Sport",USA,113 min,PG-13,5.8,NaN,3.3,65.0
...,...,...,...,...,...,...,...,...,...,...,...
0,Gran_Torino,"English, Hmong",2008,Drama,"USA, Germany",116 min,R,8.2,7.1,4.1,72.0
0,Good_Will_Hunting,English,1997,Drama,USA,126 min,R,8.3,8.0,3.9,70.0
0,"The_Good,_the_Bad_and_the_Ugly",Italian,1966,Western,"Italy, Spain, West Germany, USA",161 min,NOT RATED,8.9,8.8,4.0,90.0
0,Ratatouille,"English, French",2007,"Animation, Comedy, Family",USA,111 min,G,8.0,8.5,3.9,96.0
0,Oorlogswinter,Dutch,1975,Drama,Netherlands,325 min,N/A,6.7,NaN,NaN,NaN

In [52]:
df_join = pd.merge(df_ground, out_df, on="filename", how="inner")

In [53]:
df_join = df_join.sort_values("filename")
df_join

,movie,filename,goodforairplane,language,year,genre,country,runtime,rated,imdbRating,tomatoRating,tomatoUserRating,metascore
0,10.000 Km,10.000_Km,1,"Spanish, Catalan, English",2014,"Comedy, Drama, Romance",Spain,99 min,R,6.8,7.0,3.7,NaN
1,12 Years a Slave,12_Years_a_Slave,1,English,2013,"Biography, Drama, History","USA, UK",134 min,R,8.1,NaN,NaN,97.0
3,21 Jump Street,21_Jump_Street,1,English,2012,"Action, Comedy, Crime",USA,109 min,R,7.2,7.2,4.0,69.0
2,2 States,2_States,1,Hindi,2014,"Comedy, Drama, Romance",India,149 min,NOT RATED,7.1,NaN,3.6,NaN
4,A Bug's Life,A_Bug's_Life,1,English,1998,"Animation, Adventure, Comedy",USA,95 min,G,7.2,NaN,NaN,77.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
218,X-Men Days of Future Past,X-Men__Days_of_Future_Past,0,"English, Vietnamese, French",2014,"Action, Adventure, Sci-Fi","USA, UK",131 min,PG-13,8.1,7.6,4.3,74.0
219,X-Men First Class,X-Men__First_Class,0,"English, German, French, Spanish, Russian",2011,"Action, Adventure, Sci-Fi","USA, UK",132 min,PG-13,7.8,7.4,4.0,65.0
220,Yentl,Yentl,1,English,1983,"Drama, Musical, Romance","UK, USA",132 min,PG,6.6,6.0,3.5,NaN
221,Yves Saint Laurent,Yves_Saint_Laurent,0,"French, English, Russian, Arabic, Japanese",2014,"Biography, Drama","France, Belgium",106 min,R,6.2,5.3,3.1,51.0
222,Zombieland,Zombieland,0,English,2009,"Comedy, Horror",USA,88 min,R,7.7,7.4,3.5,73.0

In [54]:
df_join = df_join.drop(["movie", "filename"], axis=1)

In [55]:
import numpy as np

count=0
for i in df_join["genre"].values:
    df_join["genre"].values[count] = i.replace(" ", "")
    count+=1
    
count=0
for i in df_join["language"].values:
    df_join["language"].values[count] = i.replace(" ", "")
    count+=1
    
    
count=0
for i in df_join["country"].values:
    df_join["country"].values[count] = i.replace(" ", "")
    count+=1

In [56]:
genre = df_join.genre.str.split(",", expand=True).stack()
language = df_join.language.str.split(",", expand=True).stack()
country = df_join.country.str.split(",", expand=True).stack()

In [57]:
df_join = pd.concat([df_join, 
                pd.get_dummies(genre, prefix="g").groupby(level=0).sum()],axis=1) \
                .drop(["genre"],axis=1)

df_join = pd.concat([df_join, 
                pd.get_dummies(language, prefix="l").groupby(level=0).sum()],axis=1) \
                .drop(["language"],axis=1)

df_join = pd.concat([df_join, 
                pd.get_dummies(country, prefix="c").groupby(level=0).sum()],axis=1) \
                .drop(["country"],axis=1)

In [58]:
df_join.columns
df_join["runtime"] = df_join["runtime"].apply(lambda x: x.split(" min")[0])
df_join["runtime"] = df_join["runtime"].apply(pd.to_numeric, errors="coerce")

In [60]:
df_join.to_csv("../../Results/metadata_test_plus_ratings_sorted.csv",index=False)